-- =====================================================================
-- ANJIR — Slice 3: staff dashboards
-- Adds RLS for staff-authenticated operations, seeds a test store owner,
-- and indexes for the orders inbox queries.
-- =====================================================================

-- =====================================================================
-- Policies for staff actions
-- For Slice 3 we operate via the service role from server routes
-- (which bypasses RLS), so we don't need fine-grained staff policies yet.
-- But we DO need to allow reads from anon for the operator inbox to work
-- if it ever goes through anon. For now, we use service role exclusively
-- for /api/staff/* routes — see src/lib/supabase/admin.ts.
--
-- When we move to direct anon access in Slice 4 with realtime, we'll add
-- per-role policies here.
-- =====================================================================

-- Allow updating orders (status transitions by staff via service role)
drop policy if exists "staff update orders" on orders;
create policy "staff update orders" on orders for update using (true) with check (true);

-- Allow staff to update store metadata (hours, pause, etc.) via service role
drop policy if exists "staff update stores" on stores;
create policy "staff update stores" on stores for update using (true) with check (true);

-- Allow staff to update/insert products via service role
drop policy if exists "staff manage products" on products;
create policy "staff manage products" on products for all using (true) with check (true);

-- Allow staff to insert order events
drop policy if exists "staff insert events" on order_events;
create policy "staff insert events" on order_events for insert with check (true);

-- =====================================================================
-- Index for the store orders inbox — partial index for active orders
-- =====================================================================

create index if not exists idx_orders_store_active
  on orders(store_id, created_at desc)
  where status not in ('delivered', 'cancelled');

-- =====================================================================
-- Seed: store_owner user linked to the demo store
--
-- Phone: +992900000000
-- Password: anjir2025
-- The password_hash below is PBKDF2-SHA256 with 600000 iterations,
-- generated by the same function in src/lib/staff/password.ts.
-- =====================================================================

insert into users (id, phone, name, role, password_hash, locale)
values (
  '22222222-2222-2222-2222-222222222222',
  '+992900000000',
  'Демо Боғбон',
  'store_owner',
  'pbkdf2$600000$YW5qaXJfZGVtb19zYWx0Xw$U5Y3sfPC7I6JOGp2P7P-wpPMAu2G7NugWkMd5V_7fQs',
  'ru'
)
on conflict (phone) do nothing;

-- Link the demo store to this owner
update stores
set owner_id = '22222222-2222-2222-2222-222222222222'
where id = '11111111-1111-1111-1111-111111111111';

-- =====================================================================
-- Operator user
--
-- Phone: +992900000001
-- Password: anjir2025
-- =====================================================================

insert into users (id, phone, name, role, password_hash, locale)
values (
  '33333333-3333-3333-3333-333333333333',
  '+992900000001',
  'Оператор',
  'operator',
  'pbkdf2$600000$YW5qaXJfZGVtb19zYWx0Xw$U5Y3sfPC7I6JOGp2P7P-wpPMAu2G7NugWkMd5V_7fQs',
  'ru'
)
on conflict (phone) do nothing;
